// Get correct asset path with base URL
const BASE_URL = import.meta.env.BASE_URL || '/'

export function getAssetUrl(path: string): string {
  // If already a full URL or data URL, return directly
  if (path.startsWith('http') || path.startsWith('data:')) {
    return path
  }
  
  // Remove leading slash
  const cleanPath = path.startsWith('/') ? path.slice(1) : path
  
  // Concatenate base URL
  return `${BASE_URL}${cleanPath}`
}

// Image path constants
export const IMAGES = {
  background: getAssetUrl('/img/background.jpg'),
  avatar: getAssetUrl('/img/avatar.webp'),
  defaultCover: getAssetUrl('/img/default-cover.webp'),
  aboutBg: getAssetUrl('/img/about-bg.webp'),
  archiveBg: getAssetUrl('/img/archive-bg.webp'),
  animeRainbowLandscape: getAssetUrl('/img/anime-rainbow-landscape.webp'),
  fantasyAnimeScene: getAssetUrl('/img/fantasy-anime-style-scene.webp'),
  illustrationAnimeCity: getAssetUrl('/img/illustration-anime-city.webp'),
  animeCharactersSpace: getAssetUrl('/img/anime-style-characters-space.webp'),
  fantasyMagicLandscape: getAssetUrl('/img/fantasy-magic-landscape.webp'),
  animeLandscapeTraveling: getAssetUrl('/img/anime-landscape-person-traveling.webp'),
  animeCharacterTraveling: getAssetUrl('/img/anime-character-traveling.webp'),
  qqQrCode: getAssetUrl('/img/QQ.png'),
  zhoushuhuizhan: getAssetUrl('/img/zhoushuhuizhan.webp'),
  // Anime covers
  jojo: getAssetUrl('/img/jojo.webp'),
  shilaimu: getAssetUrl('/img/shilaimu.webp'),
  wenhaoyequan: getAssetUrl('/img/wenhaoyequan.webp'),
  jiandieguojiajia: getAssetUrl('/img/jiandieguojiajia.webp'),
  xiamuyourenzhang: getAssetUrl('/img/xiamuyourenzhang.webp'),
  feichangkeai: getAssetUrl('/img/feichangkeai.webp'),
  xugoutuili: getAssetUrl('/img/xugoutuili.webp'),
  huiyedaxiaojie: getAssetUrl('/img/huiyedaxiaojie.webp'),
  luren: getAssetUrl('/img/luren.webp'),
  shishou: getAssetUrl('/img/shishou.webp'),
  quanyecha: getAssetUrl('/img/quanyecha.webp'),
  wanitasi: getAssetUrl('/img/wanitasi.webp'),
  likelisi: getAssetUrl('/img/likelisi.webp'),
  tari: getAssetUrl('/img/tari.webp'),
  weiwenhuaming: getAssetUrl('/img/weiwenhuaming.webp'),
  siyue: getAssetUrl('/img/siyue.webp'),
  chenxi: getAssetUrl('/img/chenxi.webp'),
  chunwu: getAssetUrl('/img/chunwu.webp'),
  clannad: getAssetUrl('/img/clannad.webp'),
  yinghuazhuang: getAssetUrl('/img/yinghuazhuang.webp'),
  zeroone: getAssetUrl('/img/zeroone.webp'),
  buxiaomao: getAssetUrl('/img/buxiaomao.webp'),
  baixiang: getAssetUrl('/img/baixiang.webp'),
  bingguo: getAssetUrl('/img/bingguo.webp'),
  onepiece: getAssetUrl('/img/onepiece.webp'),
  naruto: getAssetUrl('/img/naruto.webp'),
  dragonball: getAssetUrl('/img/dragonball.webp'),
  yiquan: getAssetUrl('/img/yiquan.webp'),
  re: getAssetUrl('/img/re.webp'),
  shuangchengzhizhan: getAssetUrl('/img/shuangchengzhizhan.webp'),
  eightysixbu: getAssetUrl('/img/86bu.webp'),
  jinjidejuren: getAssetUrl('/img/jinjidejuren.webp'),
  // Movie covers
  qianren3: getAssetUrl('/img/qianren3.webp'),
  yinglunduijue: getAssetUrl('/img/yinglunduijue.webp'),
  jirikuaile: getAssetUrl('/img/jirikuaile.webp'),
  aiqinggongyu: getAssetUrl('/img/aiqinggongyu.webp'),
  handoutegong3: getAssetUrl('/img/handoutegong3.webp'),
  yaoshen: getAssetUrl('/img/yaoshen.webp'),
  feichirensheng: getAssetUrl('/img/feichirensheng.webp'),
  kuangrexingdong: getAssetUrl('/img/kuangrexingdong.webp'),
  tianqizhizi: getAssetUrl('/img/tianqizhizi.webp'),
  mishitaotuo: getAssetUrl('/img/mishitaotuo.webp'),
  wusha: getAssetUrl('/img/wusha.webp'),
  ziluolan: getAssetUrl('/img/ziluolan.webp'),
  tangtan3: getAssetUrl('/img/tangtan3.webp'),
  feihongdezidan: getAssetUrl('/img/feihongdezidan.webp'),
  wodejiejie: getAssetUrl('/img/wodejiejie.webp'),
  hongfageji: getAssetUrl('/img/hongfageji.webp'),
  manjianghong: getAssetUrl('/img/manjianghong.webp'),
  baonipingan: getAssetUrl('/img/baonipingan.webp'),
  lingyazhilv: getAssetUrl('/img/lingyazhilv.webp'),
  guzhuyizhi: getAssetUrl('/img/guzhuyizhi.webp'),
  qianren4: getAssetUrl('/img/qianren4.webp'),
  feichirensheng2: getAssetUrl('/img/feichirensheng2.webp'),
  yaotaiyang: getAssetUrl('/img/yaotaiyang.webp'),
  wusha3: getAssetUrl('/img/wusha3.webp'),
  nezha2: getAssetUrl('/img/nezha2.webp'),
  liejinyouxi: getAssetUrl('/img/liejinyouxi.webp'),
  huihuaqiyuji: getAssetUrl('/img/huihuaqiyuji.webp'),
  nisha: getAssetUrl('/img/nisha.webp'),
  langlangrensheng: getAssetUrl('/img/langlangrensheng.webp'),
  xiaoshuojia2: getAssetUrl('/img/xiaoshuojia2.webp'),
  bizhengming: getAssetUrl('/img/bizhengming.webp'),
  sishenlaile: getAssetUrl('/img/sishenlaile.webp'),
  bufengzhuoying: getAssetUrl('/img/bufengzhuoying.webp'),
  eyi: getAssetUrl('/img/eyi.webp'),
  xiaoyaoguai: getAssetUrl('/img/xiaoyaoguai.webp'),
  dongwucheng2: getAssetUrl('/img/dongwucheng2.webp'),
  jixianfeng: getAssetUrl('/img/jixianfeng.webp'),
  nvwushen: getAssetUrl('/img/nvwushen.webp'),
  xunxianghuaduo: getAssetUrl('/img/xunxianghuaduo.webp'),
  // TV Series covers
  baisuizhihao: getAssetUrl('/img/baisuizhihao.webp'),
  xinghancanlan: getAssetUrl('/img/xinghancanlan.webp'),
  angelidemimi: getAssetUrl('/img/angelidemimi.webp'),
  nanhong: getAssetUrl('/img/nanhong.webp'),
  toutoucangbuzhu: getAssetUrl('/img/toutoucangbuzhu.webp'),
  relian: getAssetUrl('/img/relian.webp'),
  xuwoyaoyan: getAssetUrl('/img/xuwoyaoyan.webp'),
  ruqingyun: getAssetUrl('/img/ruqingyun.webp'),
  baoxue: getAssetUrl('/img/baoxue.webp'),
  shidai: getAssetUrl('/img/shidai.webp'),
  zhaoxuelu: getAssetUrl('/img/zhaoxuelu.webp'),
  tingshuonixihuan: getAssetUrl('/img/tingshuonixihuan.webp'),
  pinuocao: getAssetUrl('/img/pinuocao.webp'),
  dushiaiqing: getAssetUrl('/img/dushiaiqing.webp'),
  renyiyilian: getAssetUrl('/img/renyiyilian.webp'),
  dangnichenshui: getAssetUrl('/img/dangnichenshui.webp'),
  strangerthings: getAssetUrl('/img/strangerthings.webp'),
  // Game covers
  lol: getAssetUrl('/img/LOL.jpg'),
  csgo: getAssetUrl('/img/csgo.jpeg'),
  guailieshijie: getAssetUrl('/img/guailieshijie.jpg'),
  nba2k25: getAssetUrl('/img/2k25.webp'),
  heiwukong: getAssetUrl('/img/heiwukong.webp'),
  nba2k24: getAssetUrl('/img/2k24.avif'),
  dabiaoke2: getAssetUrl('/img/dabiaoke2.jpg'),
  nba2k23: getAssetUrl('/img/2k23.webp'),
  zhilang: getAssetUrl('/img/zhilang.jpeg'),
  paidui: getAssetUrl('/img/zoujipaidui.webp'),
  shuangrenchengxing: getAssetUrl('/img/shuangrenchengxing.jpg'),
  sifu: getAssetUrl('/img/sifu.webp'),
  kakaluote: getAssetUrl('/img/kakaluote.jpg'),
  qiushengzhilu2: getAssetUrl('/img/qiushengzhilu2.webp'),
  pubg: getAssetUrl('/img/PUBG.webp'),
  forest: getAssetUrl('/img/forest.webp'),
  jumpforce: getAssetUrl('/img/jumpforce.jpg'),
  backrooms: getAssetUrl('/img/backrooms.webp'),
  wushi3: getAssetUrl('/img/wushi3.webp'),
  tangdouren: getAssetUrl('/img/tangdouren.jpeg'),
  tiequan7: getAssetUrl('/img/tiequan7.jpeg'),
  apex: getAssetUrl('/img/apex.jpeg'),
  zhiminggongsi: getAssetUrl('/img/zhiminggongsi.webp'),
  picopark: getAssetUrl('/img/picopark.webp'),
  nvwulaile: getAssetUrl('/img/nvwulaile.jpg'),
  eyasha: getAssetUrl('/img/eyasha.webp'),
  dongrijihua: getAssetUrl('/img/dongrijihua.jpeg'),
  xiangjiaoqiangdao: getAssetUrl('/img/xiangjiaoqiangdao.jpg'),
  yongjiewujian: getAssetUrl('/img/yongjiewujian.webp'),
  laotouhuan: getAssetUrl('/img/laotouhuan.webp'),
  wenming6: getAssetUrl('/img/wenming6.jpg'),
  youlingxian: getAssetUrl('/img/youlingxian.webp'),
  payday2: getAssetUrl('/img/payday2.webp'),
  jixiandianfeng: getAssetUrl('/img/jixiandianfeng.webp'),
  jipinfeiche: getAssetUrl('/img/jipinfeiche.webp'),
  wuzhuzhidi2: getAssetUrl('/img/wuzhuzhidi2.webp'),
  zuqiu2022: getAssetUrl('/img/zuqiu2022.jpg'),
  zuqiu2024: getAssetUrl('/img/zuqiu2024.webp'),
  siwanggeqian: getAssetUrl('/img/siwanggeqian.webp'),
  mingyun2: getAssetUrl('/img/mingyun2.jpg'),
  gumuliying: getAssetUrl('/img/gumuliying.jpg'),
  xiaoguang: getAssetUrl('/img/xiaoguang.jpg'),
  supulalan: getAssetUrl('/img/supulalan.avif'),
  youlingxingzhe: getAssetUrl('/img/youlingxingzhe.jpg'),
  youlingxingzhe2: getAssetUrl('/img/youlingxingzhe2.jpeg'),
  moninongchang22: getAssetUrl('/img/moninongchang22.jpg'),
  hunaobanjia: getAssetUrl('/img/hunaobanjia.jpg'),
  monibashi21: getAssetUrl('/img/monibashi21.webp'),
  siwangdao2: getAssetUrl('/img/siwangdao2.webp'),
  yixinghuanwei: getAssetUrl('/img/yixinghuanwei.webp'),
  fangzhou: getAssetUrl('/img/fangzhou.webp'),
  nba2k26: getAssetUrl('/img/2k26.webp'),
  yingzhiren: getAssetUrl('/img/yingzhiren.jpg'),
  guailiehuangye: getAssetUrl('/img/guailiehuangye.jpeg'),
  bodezhimen3: getAssetUrl('/img/bodezhimen3.webp'),
  valorant: getAssetUrl('/img/valorant.webp'),
}

// Cover image pool
export const COVER_IMAGES = [
  IMAGES.animeRainbowLandscape,
  IMAGES.fantasyAnimeScene,
  IMAGES.illustrationAnimeCity,
  IMAGES.animeCharactersSpace,
  IMAGES.fantasyMagicLandscape,
  IMAGES.animeLandscapeTraveling,
  IMAGES.animeCharacterTraveling,
]

// Get cover image by string hash
export function getCoverImage(seed: string): string {
  const hash = seed.split('').reduce((a, b) => ((a << 5) - a) + b.charCodeAt(0), 0)
  const index = Math.abs(hash) % COVER_IMAGES.length
  return COVER_IMAGES[index]
}
